GET http://localhost:3000/batches

###

POST http://localhost:3000/batches
Content-Type: application/json

{
    "executionDate": "2021-01-15",
    "lastEventId": 998584,
    "deltaSize": 40
}
###

PATCH http://localhost:3000/batches/one/6045c8eca564493a750ad623
Content-Type: application/json

{
    "lastEventId": 999997
}

###

DELETE http://localhost:3000/batches/one/60442bc83d0f424719ca3241

###

DELETE http://localhost:3000/batches/all
