GET http://localhost:3000/covid/total?symptomDateFrom=2020-05-29&symptomDateTo=2020-05-31&ageFrom=65&ageTo=80&genre=M&state=Buenos%20Aires

###

GET http://localhost:3000/covid/deaths

###

GET http://localhost:3000/covid/update

###

POST http://localhost:3000/covid/update