GET http://localhost:3000/occurrences

###

POST http://localhost:3000/occurrences
Content-Type: application/json

{
    "eventId": 998584,
    "symptomDate": "2021-01-15",
    "age": 65,
    "genre": "M",
    "state": "Buenos Aires",
    "deceased": "NO"
}

###

DELETE http://localhost:3000/occurrences/one/6045c8eca564493a750ad622

###

DELETE http://localhost:3000/occurrences/all
